server:
  port: 8081

### Actuator config #########
management:
  endpoints:
    web:
      base-path: /_service/
      path-mapping:
        info: /info

### deploy info #########
info.deploy.region: reg-01
